In [1]:
import pandas as pd
import numpy as np
import sqlite3
from sqlalchemy.engine import create_engine

In [2]:
used_cols = ['item_id','category_name','price']

Create a databas called avito.db and add train.csv into the database

In [3]:
# ONLY NEED TO DO ONCE TO CREATE DATABASE
df = pd.read_csv('data/train.csv').dropna()
avito = sqlite3.connect("avito.db")
df.to_sql('data/train', avito)

df = pd.read_csv('data/periods_train.csv').dropna()
avito = sqlite3.connect("avito.db")
df.to_sql('data/periods_train', avito)

ValueError: Table 'data/train' already exists.

In [4]:
train_active = pd.read_csv('data/train_active.csv', usecols=used_cols).dropna()
train_active.head()

        item_id              category_name     price
0  70d6342079ef            Книги и журналы     200.0
1  97cf505710e1       Гаражи и машиноместа  590000.0
2  6a93a31a945d  Коммерческая недвижимость  100000.0
3  050cade37667                   Телефоны     750.0
4  2935e85aa40b     Ремонт и строительство    3900.0

In [5]:
cate_train_active = train_active.groupby('category_name').agg({'price': [np.mean, np.std]})
cate_train_active

                                     price
                                      mean           std
category_name
Автомобили                    1.998291e+06  8.056998e+08
Аквариум                      5.998453e+03  3.952939e+05
Аудио и видео                 4.211682e+05  1.951476e+08
Билеты и путешествия          1.533720e+05  1.134955e+07
Бытовая техника               6.235100e+03  3.294328e+04
Велосипеды                    1.138108e+04  3.515388e+05
Водный транспорт              6.716305e+05  1.072171e+07
Гаражи и машиноместа          3.036546e+05  3.701491e+06
Готовый бизнес                5.210861e+06  3.776421e+07
Грузовики и спецтехника       9.706566e+05  2.908503e+07
Детская одежда и обувь        4.150684e+03  9.623938e+05
Дома, дачи, коттеджи          3.589224e+06  2.400498e+08
Другие животные               2.839487e+05  4.437755e+07
Земельные участки             3.000343e+06  2.783598e+08
Игры, приставки и программы   1.075776e+06  3.269897e+08
Квартиры                      2.348649e+06  1.557441e+08
Книги и журналы               1.481557e+04  1.779879e+06
Коллекционирование            2.367888e+04  5.269845e+06
Коммерческая недвижимость     7.806032e+06  2.314405e+08
Комнаты                       4.641466e+05  6.598083e+05
Кошки                         2.730846e+06  4.897821e+08
Красота и здоровье            1.343306e+04  2.995908e+06
Мебель и интерьер             8.636070e+03  2.445879e+05
Мотоциклы и мототехника       1.576363e+05  3.536323e+05
Музыкальные инструменты       2.776946e+04  2.026914e+06
Настольные компьютеры         1.411500e+04  6.645381e+04
Недвижимость за рубежом       1.636055e+07  2.235796e+08
Ноутбуки                      1.437247e+04  2.497200e+04
Оборудование для бизнеса      4.134018e+05  6.636048e+07
Одежда, обувь, аксессуары     7.300580e+03  3.395165e+06
Оргтехника и расходники       6.300002e+03  3.450852e+05
Охота и рыбалка               7.091058e+03  2.894036e+05
Планшеты и электронные книги  5.095357e+03  1.297225e+05
Посуда и товары для кухни     6.364772e+03  1.181863e+06
Предложение услуг             1.345329e+06  3.418542e+08
Продукты питания              3.269478e+06  5.233584e+08
Птицы                         3.260447e+06  5.390361e+08
Растения                      1.615549e+03  3.774418e+04
Ремонт и строительство        3.895836e+04  1.929319e+07
Собаки                        2.753310e+07  4.703300e+09
Спорт и отдых                 9.816879e+03  6.040763e+05
Телефоны                      8.581557e+05  4.883707e+08
Товары для детей и игрушки    1.275746e+05  1.047623e+08
Товары для животных           5.686184e+03  4.801576e+05
Товары для компьютера         4.169234e+03  7.695434e+05
Фототехника                   8.053090e+03  9.243244e+04
Часы и украшения              8.974114e+03  2.421673e+05

In [6]:
cate_train_active.to_csv('cate_price.csv')

In [7]:
#cate_train_active['price']['mean']

category_name
Автомобили                      1.998291e+06
Аквариум                        5.998453e+03
Аудио и видео                   4.211682e+05
Билеты и путешествия            1.533720e+05
Бытовая техника                 6.235100e+03
Велосипеды                      1.138108e+04
Водный транспорт                6.716305e+05
Гаражи и машиноместа            3.036546e+05
Готовый бизнес                  5.210861e+06
Грузовики и спецтехника         9.706566e+05
Детская одежда и обувь          4.150684e+03
Дома, дачи, коттеджи            3.589224e+06
Другие животные                 2.839487e+05
Земельные участки               3.000343e+06
Игры, приставки и программы     1.075776e+06
Квартиры                        2.348649e+06
Книги и журналы                 1.481557e+04
Коллекционирование              2.367888e+04
Коммерческая недвижимость       7.806032e+06
Комнаты                         4.641466e+05
Кошки                           2.730846e+06
Красота и здоровье              1.343306e+04
Мебель и интерьер               8.636070e+03
Мотоциклы и мототехника         1.576363e+05
Музыкальные инструменты         2.776946e+04
Настольные компьютеры           1.411500e+04
Недвижимость за рубежом         1.636055e+07
Ноутбуки                        1.437247e+04
Оборудование для бизнеса        4.134018e+05
Одежда, обувь, аксессуары       7.300580e+03
Оргтехника и расходники         6.300002e+03
Охота и рыбалка                 7.091058e+03
Планшеты и электронные книги    5.095357e+03
Посуда и товары для кухни       6.364772e+03
Предложение услуг               1.345329e+06
Продукты питания                3.269478e+06
Птицы                           3.260447e+06
Растения                        1.615549e+03
Ремонт и строительство          3.895836e+04
Собаки                          2.753310e+07
Спорт и отдых                   9.816879e+03
Телефоны                        8.581557e+05
Товары для детей и игрушки      1.275746e+05
Товары для животных             5.686184e+03
Товары для компьютера           4.169234e+03
Фототехника                     8.053090e+03
Часы и украшения                8.974114e+03
Name: mean, dtype: float64

Calculate price normal

In [8]:
train = pd.read_csv('data/train.csv', usecols=used_cols)
#train = pd.read_csv('data/train.csv', usecols=used_cols).dropna()
train['category_name'].nunique()
train['price_normal'] = 0
train.head()

        item_id               category_name    price  price_normal
0  b912c3c6a6ad  Товары для детей и игрушки    400.0             0
1  2dac0150717d           Мебель и интерьер   3000.0             0
2  ba83aefab5dc               Аудио и видео   4000.0             0
3  02996f1dd2ea  Товары для детей и игрушки   2200.0             0
4  7c90be56d2ab                  Автомобили  40000.0             0

In [12]:
cate_train_active = pd.read_csv('cate_price.csv')
cate_train_active.head()

      Unnamed: 0               price            price.1
0            NaN                mean                std
1  category_name                 NaN                NaN
2     Автомобили  1998291.3617995717  805699762.4769341
3       Аквариум   5998.452698652339  395293.9137120012
4  Аудио и видео   421168.1808828096  195147613.3348211

In [10]:
# TEST IF TRAIN MAKES SENSE
cate_train = train.groupby('category_name').agg({'price': [np.mean, np.std]})
cate_train

                                     price
                                      mean           std
category_name
Автомобили                    3.779836e+05  5.233088e+05
Аквариум                      3.149496e+03  4.295776e+04
Аудио и видео                 7.518729e+03  1.979137e+05
Билеты и путешествия          2.202707e+04  1.883342e+05
Бытовая техника               7.944267e+03  4.743349e+04
Велосипеды                    8.177324e+03  3.610675e+04
Водный транспорт              2.665777e+05  1.190153e+06
Гаражи и машиноместа          2.651850e+05  8.683569e+05
Готовый бизнес                2.906996e+06  1.348665e+07
Грузовики и спецтехника       7.629971e+05  1.923954e+06
Детская одежда и обувь        9.787546e+03  1.486987e+06
Дома, дачи, коттеджи          2.651154e+06  6.376355e+06
Другие животные               1.146810e+05  3.135282e+06
Земельные участки             8.210750e+06  6.690735e+08
Игры, приставки и программы   7.701659e+03  2.018666e+05
Квартиры                      2.003441e+06  4.892577e+06
Книги и журналы               1.093600e+04  8.315741e+05
Коллекционирование            4.251077e+04  3.340481e+06
Коммерческая недвижимость     6.735045e+06  2.935463e+07
Комнаты                       4.029475e+05  4.569551e+05
Кошки                         1.666761e+04  3.859000e+05
Красота и здоровье            4.512370e+03  1.954273e+05
Мебель и интерьер             3.220149e+04  3.555820e+06
Мотоциклы и мототехника       1.287009e+05  3.233859e+05
Музыкальные инструменты       1.254745e+04  4.192234e+04
Настольные компьютеры         1.297918e+04  3.030708e+04
Недвижимость за рубежом       1.154915e+07  4.261463e+07
Ноутбуки                      1.318337e+04  1.322197e+04
Оборудование для бизнеса      3.937724e+05  2.183494e+07
Одежда, обувь, аксессуары     8.243247e+03  1.160211e+06
Оргтехника и расходники       5.388955e+03  7.882771e+04
Охота и рыбалка               4.617569e+03  1.264470e+04
Планшеты и электронные книги  5.086037e+03  6.267558e+03
Посуда и товары для кухни     2.470037e+03  2.987933e+04
Предложение услуг             1.321863e+04  8.581824e+05
Продукты питания              1.020555e+03  1.867327e+04
Птицы                         3.500596e+04  1.285403e+06
Растения                      2.259273e+03  2.953192e+04
Ремонт и строительство        2.123771e+04  8.050969e+05
Собаки                        1.030408e+04  1.263263e+05
Спорт и отдых                 1.037242e+04  4.545453e+05
Телефоны                      3.008696e+04  2.677769e+06
Товары для детей и игрушки    4.129398e+03  1.353662e+05
Товары для животных           6.029656e+03  1.802225e+05
Товары для компьютера         1.943345e+04  2.145366e+06
Фототехника                   9.029348e+03  2.345227e+04
Часы и украшения              1.335892e+04  5.310464e+05

In [11]:
for i, item in enumerate(train['item_id'][0:]):    
    for j, cate in enumerate(cate_train_active['category_name']):
#        print(i, train['category_name'][i], cate)
        if train['category_name'][i] == cate:
#            print(train['category_name'][i])
#            print(cate)
#            print(train['price'][i])
#            print(cate_train_active['price_std'][j])
#            print(cate_train_active['price_mean'][j])
            train['price_normal'][i] = (train['price'][i] - cate_train_active['price_mean'][j])/cate_train_active['price_std'][j]

KeyError: 'category_name'

In [ ]:
train['price_normal']

In [ ]:
train.to_csv('train_price_normal.csv')

Select the item_id term only

In [ ]:
#item = pd.read_sql('SELECT item_id,category_name,price FROM train_active WHERE price > 10000', avito)

SELECT all items with price > 10000

In [ ]:
#price = pd.read_sql('SELECT * FROM train WHERE price > 10000 ', avito)
#price