# Main?
Alireza: I envisioned that this notebook can be the main training pipeline that calls on various function to generate clean features for the given list of item_id. These dataframes will be merged/joined on item_id and that final dataframe can be used for training and ensembling.

*Note: if this format is acceptable by you, it is preferrable to always pull the latest version of this notebook and then make a pull request (PR) for changing it as it is one of the main files where collaboration happens hence a high chance of unwanted merge conflicts!

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
from utils import generate_periods_features
%matplotlib inline

In [2]:
train_periods_file = 'data/periods_train_featurized.csv'
## 1) when the featurization needs to be refreshed:
train_periods = pd.read_csv('data/periods_train.csv')
# train_periods = generate_periods_features(train_periods)
# train_periods.set_index('item_id').to_csv(train_periods_file)

## 2) when there is a featurized csv is already available on your disk
# train_periods = pd.read_csv(train_periods_file)

AssertionError:

In [4]:
len(train_periods) == len(train_periods.drop_duplicates('item_id'))

False

In [10]:
train_periods[train_periods['item_id'].duplicated()]

               item_id activation_date  date_from    date_to
9581      7fb2f7c83c6f      2017-02-13 2017-03-15 2017-03-15
14114     2cc9137abee8      2017-02-21 2017-03-15 2017-03-23
20922     abf7a10c3a0c      2017-02-15 2017-03-15 2017-03-17
21387     416a2e2cba8b      2017-02-19 2017-03-15 2017-03-21
23473     00b26bf899b0      2017-02-25 2017-03-15 2017-03-26
25369     0fa8b4a068e9      2017-02-16 2017-03-15 2017-03-18
28120     4641c59a4365      2017-02-19 2017-03-15 2017-03-21
28503     b56ed1d31fe3      2017-02-16 2017-03-15 2017-03-18
29141     8cd30f3fae22      2017-02-22 2017-03-15 2017-03-24
31329     6bf6a8d12bcf      2017-03-20 2017-03-20 2017-03-28
32022     8475c63479cc      2017-03-24 2017-03-24 2017-03-28
32735     7b83dd3bf9f4      2017-02-15 2017-03-15 2017-03-16
33034     c9477ffb7b70      2017-02-15 2017-03-15 2017-03-16
34955     dd470b895e86      2017-02-14 2017-03-15 2017-03-16
37241     7df9418bbdf1      2017-02-26 2017-03-15 2017-03-27
37719     ed80ef4be317      2017-02-24 2017-03-15 2017-03-26
38267     a6e0db188bc8      2017-02-18 2017-03-15 2017-03-20
39229     a0cb75262af8      2017-03-23 2017-03-23 2017-03-28
39240     9f3309963d16      2017-02-18 2017-03-15 2017-03-20
39895     018233c60be1      2017-03-28 2017-03-28 2017-03-28
40766     2ccdbd10d3f3      2017-03-19 2017-03-19 2017-03-28
42229     9eac8e5ab142      2017-03-19 2017-03-19 2017-03-28
43764     f8b5dd2d23e4      2017-03-22 2017-03-22 2017-03-28
44724     bbdc69e839b8      2017-03-24 2017-03-24 2017-03-28
46440     b9e714895540      2017-02-17 2017-03-15 2017-03-18
47102     214dee142fc3      2017-03-23 2017-03-23 2017-03-28
48196     dece62c6dff8      2017-03-27 2017-03-27 2017-03-28
48302     1fa709353a9a      2017-02-22 2017-03-15 2017-03-24
49418     c80dbffdef49      2017-03-28 2017-03-28 2017-03-28
49717     f4ca52bbe0bb      2017-02-13 2017-03-15 2017-03-15
...                ...             ...        ...        ...
16687341  8b303211d8b2      2017-03-24 2017-03-24 2017-03-28
16687342  eab012349bb6      2017-03-25 2017-03-25 2017-03-28
16687343  f82d5c16986c      2017-02-19 2017-03-15 2017-03-21
16687344  528b929e4909      2017-02-15 2017-03-15 2017-03-17
16687346  ef72e2aae7ee      2017-03-22 2017-03-22 2017-03-28
16687347  5b52c07c7f6c      2017-03-25 2017-03-25 2017-03-28
16687348  67fc843077fe      2017-03-28 2017-03-28 2017-03-28
16687352  ed6f71b9f45f      2017-03-28 2017-03-28 2017-03-28
16687355  c7aee7fb2649      2017-02-20 2017-03-15 2017-03-22
16687358  075753e322f9      2017-02-21 2017-03-15 2017-03-22
16687360  84d574cf6f30      2017-03-20 2017-03-20 2017-03-28
16687371  8c615450faa3      2017-02-18 2017-03-15 2017-03-19
16687374  af2efa72d7ad      2017-03-28 2017-03-28 2017-03-28
16687376  12927fba4206      2017-02-17 2017-03-15 2017-03-18
16687378  4c9cf5620766      2017-03-28 2017-03-28 2017-03-28
16687379  445a9b8d42c9      2017-03-28 2017-03-28 2017-03-28
16687380  d477609c9cec      2017-02-25 2017-03-15 2017-03-26
16687386  42b71f472e5d      2017-03-25 2017-03-25 2017-03-28
16687388  00a787860740      2017-02-19 2017-03-15 2017-03-21
16687389  e845b7754c0b      2017-02-16 2017-03-15 2017-03-18
16687392  cc2073ef643e      2017-03-27 2017-03-27 2017-03-28
16687393  b97a7e2661b0      2017-03-22 2017-03-22 2017-03-28
16687394  3a88beb67eef      2017-03-20 2017-03-20 2017-03-28
16687395  285d37e78613      2017-03-22 2017-03-22 2017-03-28
16687398  71581614720c      2017-03-27 2017-03-27 2017-03-28
16687400  c3d19f712d62      2017-02-15 2017-03-15 2017-03-16
16687402  8417f7353c57      2017-02-13 2017-03-15 2017-03-15
16687404  6310970c395f      2017-03-11 2017-03-15 2017-03-19
16687408  0e3268707b36      2017-02-26 2017-03-15 2017-03-27
16687411  0713eb82d265      2017-03-23 2017-03-23 2017-03-28

[2874866 rows x 4 columns]

In [11]:
train_periods[train_periods['item_id'] == '7fb2f7c83c6f']

           item_id activation_date  date_from    date_to
1490  7fb2f7c83c6f      2017-03-22 2017-03-22 2017-03-28
9581  7fb2f7c83c6f      2017-02-13 2017-03-15 2017-03-15

In [ ]:
test_periods_file = 'data/periods_test_featurized.csv'
## 1) when the featurization needs to be refreshed:
test_periods = pd.read_csv('data/periods_test.csv')
test_periods = generate_periods_features(test_periods)
test_periods.set_index('item_id').to_csv(test_periods_file)

## 2) when there is a featurized csv is already available on your disk
# test_periods = pd.read_csv(test_periods_file)